chapters/urls.py
from django.urls import path
from . import views

app_name = 'chapters'

urlpatterns = [
    path('create/<int:lecture_pk>/', views.create, name='create'),
    path('update/<int:lecture_pk>/<int:chapter_pk>/', views.update, name='update'),
    path('delete/<int:lecture_pk>/<int:chapter_pk>/', views.delete, name='delete'),
]

lecture_management_system/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.base),
    path('lectures/', include('lectures.urls')),
    path('chapters/', include('chapters.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lectures/urls.py
from django.urls import path
from . import views
from chapters import urls

app_name = 'lectures'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('detail/<int:lecture_pk>/', views.detail, name='detail'),
    path('update/<int:lecture_pk>/', views.update, name='update'),
    path('delete/<int:lecture_pk>/', views.delete, name='delete'),
]

chapters/models.py
from django.db import models
from lectures.models import Lecture

# Create your models here.

class Chapter(models.Model):
    lecture = models.ForeignKey(Lecture, on_delete=models.CASCADE, related_name='chapters')
    title = models.CharField(max_length=100)
    videofile = models.FileField(upload_to='videos/', null=True)

lectures/models.py
from django.db import models

# Create your models here.

class Lecture(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()

chapters/forms.py
from django import forms
from .models import Chapter

class ChapterForm(forms.ModelForm):
    class Meta:
        model = Chapter
        fields = [
            'title',
            'videofile',
        ]
        labels = {
            'title' : '제목',
            'videofile' : '동영상',
        }

lectures/forms.py
from django import forms
from .models import Lecture

class LectureForm(forms.ModelForm):
    class Meta:
        model = Lecture
        fields = [
            'title',
            'content',
        ]
        labels = {
            'title' : '제목',
            'content' : '설명',
        }

chapters/views.py
from django.shortcuts import render, redirect, get_object_or_404
from lectures.models import Lecture
from .models import Chapter
from .forms import ChapterForm

# Create your views here.

def create(request, lecture_pk):
    lecture = Lecture.objects.get(id=lecture_pk)
    if request.method == 'POST':
        form = ChapterForm(request.POST, request.FILES)
        if form.is_valid():
            form = form.save(commit=False)
            form.lecture = lecture
            form.save()
            return redirect('lectures:detail', lecture_pk=form.lecture.id)
    else:
        form = ChapterForm()
    context = {
        'form' : form,
    }
    return render(request, 'chapters/create.html', context)

def update(request, lecture_pk, chapter_pk):
    lecture = Lecture.objects.get(id=lecture_pk)
    chapter = Chapter.objects.get(id=chapter_pk)
    if request.method == 'POST':
        form = ChapterForm(request.POST, request.FILES, instance=chapter)
        if form.is_valid():
            form = form.save(commit=False)
            form.lecture = lecture
            form.save()
            return redirect('lectures:detail', lecture_pk=form.lecture.id)
    else:
        form = ChapterForm(instance=chapter)
    context = {
        'form' : form,
    }
    return render(request, 'chapters/update.html', context)

def delete(request, chapter_pk, lecture_pk):
    chapter = get_object_or_404(Chapter, pk=chapter_pk)
    chapter.delete()
    return redirect('lectures:detail', lecture_pk=lecture_pk)

lecture_management_system/views.py
from django.shortcuts import render

def base(request):
    return render(request, "base.html")

lectures/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import LectureForm
from .models import Lecture

# Create your views here.

def index(request):
    lectures = Lecture.objects.all()
    content = {
        'lectures' : lectures
    }
    return render(request, 'lectures/index.html', content)

def create(request):
    if request.method == 'POST':
        form = LectureForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('lectures:index')
    else:
        form = LectureForm()
    context = {
        'form' : form,
    }
    return render(request, 'lectures/create.html', context)

def detail(request, lecture_pk):
    lecture = get_object_or_404(Lecture, pk=lecture_pk)
    chapters = lecture.chapters.all()
    context = {
        'lecture': lecture,
        'chapters' : chapters,
    }
    return render(request, 'lectures/detail.html', context)

def update(request, lecture_pk):
    lecture = get_object_or_404(Lecture, pk=lecture_pk)
    if request.method == 'POST':
        form = LectureForm(request.POST, instance=lecture)
        if form.is_valid():
            form.save()
            return redirect('lectures:detail', lecture_pk)
    else:
        form = LectureForm(instance=lecture)
    context = {
        'form' : form,
    }
    return render(request, 'lectures/update.html', context)

def delete(request, lecture_pk):
    lecture = get_object_or_404(Lecture, pk=lecture_pk)
    lecture.delete()
    return redirect('lectures:index')

chapters/templates/chapters/create.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block content %}
  <form action="" enctype='multipart/form-data' method='POST'>
    {% csrf_token %}
    {{ form.as_p }}
    <button type='submit' class='btn btn-primary'>업로드</button>
  </form>
{% endblock content %}

chapters/templates/chapters/update.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block content %}
  <form action="" enctype='multipart/form-data' method='POST'>
    {% csrf_token %}
    {{ form.as_p }}
    <button type='submit' class='btn btn-primary'>수정</button>
  </form>
{% endblock content %}

lectures/templates/lectures/create.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block content %}
  <div class='mx-5 my-5'>
    <div class='my-3 d-flex justify-content-center'>
      <h1>
        강의 개설 페이지
      </h1>
    </div>
    <div>
      <form action="" method='POST'>
        {% csrf_token %}
        {% bootstrap_form form %}
        <button class="btn btn-ligth border-secondary rounded" type='submit'>강의 개설</button>
      </form>
    </div>
  </div>
{% endblock content %}

lectures/templates/lectures/detail.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block content %}
  <div class='mx-5 my-5'>
    <div class='d-flex justify-content-between'>
      <div>
        <div class='my-3'>
          <h3>{{ lecture.title }}</h3>
        </div>
        <hr>
        <div>
          <p>{{ lecture.content }}</p>
        </div>
      </div>
      <div class="dropdown">
        <button class="btn btn-ligth dropdown-toggle border border-secondary rounded" type="button" data-bs-toggle="dropdown" aria-expanded="false">
          강의 관리
        </button>
        <ul class="dropdown-menu" aria-labelledby="lectureActionsDropdown">
          <li>
            <a class="dropdown-item" href="{% url 'chapters:create' lecture.pk %}">챕터 만들기</a>
          </li>
          <li>
            <a class="dropdown-item" href="{% url 'lectures:update' lecture.pk %}">강의 수정</a>
          </li>
          <li>
            <a class="dropdown-item" href="{% url 'lectures:delete' lecture.pk %}">강의 삭제</a>
          </li>
          <li>
            <hr class="dropdown-divider">
          </li>
          <li>
            <a class="dropdown-item" href="{% url 'lectures:index' %}">글 목록</a>
          </li>
        </ul>
      </div>
    </div>

    <div class="border border-secondary rounded p-3">
      <h5>챕터</h5>
      <div>
        {% for chapter in chapters %}
          <div class="chapter">
            <div class="d-flex justify-content-between align-items-center">
              <h3 class="chapter-title">{{ chapter.title }}</h3>
              <div class="dropdown">
                <button class="btn btn-ligth dropdown-toggle border border-secondary rounded" type="button" id="chapterActionsDropdown{{ chapter.pk }}" data-bs-toggle="dropdown" aria-expanded="false">
                  챕터 관리
                </button>
                <ul class="dropdown-menu" aria-labelledby="chapterActionsDropdown{{ chapter.pk }}">
                  <li>
                    <a class="dropdown-item" href="{% url 'chapters:update' lecture.pk chapter.pk %}">수정하기</a>
                  </li>
                  <li>
                    <a class="dropdown-item" href="{% url 'chapters:delete' lecture.pk chapter.pk %}">삭제하기</a>
                  </li>
                </ul>
              </div>
            </div>
            <div class="chapter-content">
              <div class="ratio ratio-16x9">
                <video src="{{ chapter.videofile.url }}" controls="controls"></video>
              </div>
            </div>
          </div>
        {% endfor %}
      </div>
    </div>
  </div>

  <script>
    document.addEventListener('DOMContentLoaded', function () {
      const chapters = document.querySelectorAll('.chapter');

      chapters.forEach(function (chapter) {
        const title = chapter.querySelector('.chapter-title');
        const content = chapter.querySelector('.chapter-content');
        const dropdown = chapter.querySelector('.dropdown');

        content.style.display = 'none';
        dropdown.style.display = 'none';

        title.addEventListener('click', function () {
          if (content.style.display === 'none') {
            content.style.display = 'block';
            dropdown.style.display = 'block';
          } else {
            content.style.display = 'none';
            dropdown.style.display = 'none';
          }
        });
      });
    });
  </script>
{% endblock content %}

lectures/templates/lectures/index.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block content %}
  <div class='mx-5 my-5'>
    <div class='my-3 d-flex justify-content-center'>
      <h1>
        강의 관리 시스템
      </h1>
    </div>
    <div class='d-flex justify-content-end'>
      <a href="{% url 'lectures:create' %}">
        <button class="btn btn-ligth border-secondary rounded">강의 개설</button>
      </a>
    </div>
    <div>
      <div>
        <hr>
        {% for lecture in lectures %}
          <h5>
            <a href="{% url 'lectures:detail' lecture.pk %}" class="text-decoration-none text-black">
              {{ lecture.title }}
            </a>
          </h5>
          <hr>
        {% endfor %}
      </div>
    </div>
  </div>
{% endblock content %}

lectures/templates/lectures/update.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block content %}
  <div class='mx-5 my-5'>
    <div class='my-3'>
      강의 수정 페이지
    </div>
    <div>
      <form action="" method='POST' ,="," enctype='multipart/form-data'>
        {% csrf_token %}
        {% bootstrap_form form %}
        <button class='btn btn-primary' type='submit'>강의 수정</button>
      </form>
    </div>
  </div>
{% endblock content %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ko">

  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
  </head>

  <body>
    {% block content %}{% endblock %}
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
  </body>

</html>